[workspace]
members = [
    "crates/sleipnir-daemon",
    "crates/muninn-daemon",
    "crates/muninn-move-tracker",
    "crates/muninn-psmoveapi-tracker",
    "crates/odin-core",
    "crates/odin-daemon",
]
resolver = "3"
exclude = [
    "vendor/cultcache-rs",
    "vendor/cultnet-rs",
]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false
